[package]
name = "clickhouse-rs"
version = "0.2.0-alpha.2"
authors = ["Mikhail Sukharev <suharev7@gmail.com>"]
license = "MIT"
homepage = "https://github.com/suharev7/clickhouse-rs"
repository = "https://github.com/suharev7/clickhouse-rs"
description = "Tokio based asynchronous Yandex ClickHouse client library."
documentation = "https://docs.rs/clickhouse-rs/"
readme = "README.md"
keywords = ["tokio", "database", "clickhouse"]
categories = ["database"]
edition = "2018"
exclude = ["tests/*", "examples/*"]

[dependencies]
futures-core-preview = "=0.3.0-alpha.18"
futures-sink-preview = "=0.3.0-alpha.18"
futures-util-preview = { version = "=0.3.0-alpha.19", features = ["sink"] }

tokio = { version = "0.2.0-alpha.4", default-features = false, features = ["io", "net", "sync", "rt-full"] }
pin-project = { version = "0.4.0-alpha.11", features = ["project_attr"] }

hostname = "^0.1"

chrono = "0.4"
chrono-tz = "0.5"

lz4 = "1.23.1"
clickhouse-rs-cityhash-sys = { path = "clickhouse-rs-cityhash-sys", version = "0.1.1" }

byteorder = "^1.3"
failure = "^0.1.5"
failure_derive = "^0.1.5"
url="^2"
lazy_static = "1.4.0"

log = { version = "0.4.8", features = ["std", "serde"] }

[dev-dependencies]
env_logger = "^0.6"
rand = "^0.7"
